"""Deterministic edge projection (CAP-084B).

``EdgeProjector`` is the **sole edge authority**: it is the only component that
constructs :class:`KnowledgeEdge` instances from a resolved
:class:`~requirement_intelligence.knowledge_graph.engine.historical_dataset.
HistoricalDataset` and the nodes :class:`~requirement_intelligence.
knowledge_graph.engine.projection.node_projector.NodeProjector` already
projected. It performs **no semantic inference** — every edge it emits is one
of the governed :class:`KnowledgeEdgeType` members, named by a rule, connecting
two entity ids the historical dataset already names (Recommendation 3 of
ADR-0023: edges are governed vocabulary, never free-form). Relationship
ownership remains inside Knowledge Graph — it never re-derives a relationship a
Layer 1 subsystem already owns; it only projects the entity-id pairs the
synthetic Historical Dataset provider names.

An edge is emitted only when **both** endpoint nodes were actually projected —
this projector never manufactures a dangling reference, regardless of which
node/edge rules are policy-enabled.
"""

from __future__ import annotations

from requirement_intelligence.knowledge_graph.engine.historical_dataset import HistoricalDataset
from requirement_intelligence.knowledge_graph.identity import KnowledgeEdgeId, KnowledgeNodeId
from requirement_intelligence.knowledge_graph.models.edge import KnowledgeEdge
from requirement_intelligence.knowledge_graph.models.enums import (
    KnowledgeEdgeType,
    KnowledgeNodeType,
)
from requirement_intelligence.knowledge_graph.models.node import KnowledgeNode
from requirement_intelligence.knowledge_graph.policy import KnowledgeGraphPolicy
from requirement_intelligence.knowledge_graph.rules import (
    KnowledgeGraphRuleCatalog,
    KnowledgeGraphRuleFamily,
)

_GUIDANCE = {
    KnowledgeEdgeType.DEPENDS_ON: "a requirement depends on the requirement of the prior execution",
    KnowledgeEdgeType.GENERATED_BY: "a recommendation is generated by the requirement it addresses",
    KnowledgeEdgeType.TRACEABLE_TO: "a finding is traceable to the requirement it concerns",
    KnowledgeEdgeType.IMPLEMENTS: "a requirement implements the capability it satisfies",
    KnowledgeEdgeType.REFERENCES: "a document references the requirement it documents",
    KnowledgeEdgeType.BELONGS_TO: "a requirement belongs to the execution that produced it",
    KnowledgeEdgeType.DERIVED_FROM: "an execution is derived from the historical dataset",
    KnowledgeEdgeType.RELATED_TO: (
        "a recommendation is related to the finding recorded alongside it"
    ),
    KnowledgeEdgeType.USES: "a capability uses the document recorded alongside it",
}


def _node_id(node_type: KnowledgeNodeType, referenced_id: str) -> KnowledgeNodeId:
    return KnowledgeNodeId.for_entity(node_type.value, referenced_id)


class EdgeProjector:
    """Project governed edges connecting only already-projected nodes.

    The sole edge authority (Recommendation 1 of ADR-0023). Deduplicates by
    :class:`KnowledgeEdgeId` — the same relationship, seen more than once,
    yields exactly one edge.
    """

    def __init__(
        self, policy: KnowledgeGraphPolicy, rule_catalog: KnowledgeGraphRuleCatalog
    ) -> None:
        """Store the governed collaborators this projector reads. Construction only."""
        self._policy = policy
        self._catalog = rule_catalog

    def project(
        self, dataset: HistoricalDataset, nodes: tuple[KnowledgeNode, ...]
    ) -> tuple[KnowledgeEdge, ...]:
        """Deterministically project governed edges between already-projected nodes."""
        enabled_types = self._enabled_edge_types()
        existing_node_ids = {node.node_id for node in nodes}
        edges: dict[KnowledgeEdgeId, KnowledgeEdge] = {}

        def _link(
            edge_type: KnowledgeEdgeType,
            source_type: KnowledgeNodeType,
            source_ref: str,
            target_type: KnowledgeNodeType,
            target_ref: str,
        ) -> None:
            if edge_type not in enabled_types:
                return
            source_id = _node_id(source_type, source_ref)
            target_id = _node_id(target_type, target_ref)
            if source_id not in existing_node_ids or target_id not in existing_node_ids:
                return
            edge_id = KnowledgeEdgeId.for_relationship(
                edge_type.value, str(source_id), str(target_id)
            )
            if edge_id in edges:
                return
            edges[edge_id] = KnowledgeEdge(
                edge_id=edge_id,
                edge_type=edge_type,
                source_node_id=source_id,
                target_node_id=target_id,
                rationale=_GUIDANCE[edge_type],
            )

        executions = dataset.executions
        for index, execution in enumerate(executions):
            if execution.depends_on_previous and index > 0:
                previous = executions[index - 1]
                _link(
                    KnowledgeEdgeType.DEPENDS_ON,
                    KnowledgeNodeType.REQUIREMENT,
                    execution.requirement_id,
                    KnowledgeNodeType.REQUIREMENT,
                    previous.requirement_id,
                )

            _link(
                KnowledgeEdgeType.BELONGS_TO,
                KnowledgeNodeType.REQUIREMENT,
                execution.requirement_id,
                KnowledgeNodeType.EXECUTION,
                execution.execution_id,
            )
            _link(
                KnowledgeEdgeType.DERIVED_FROM,
                KnowledgeNodeType.EXECUTION,
                execution.execution_id,
                KnowledgeNodeType.DATASET,
                dataset.dataset_id,
            )

            if execution.recommendation_id:
                _link(
                    KnowledgeEdgeType.GENERATED_BY,
                    KnowledgeNodeType.RECOMMENDATION,
                    execution.recommendation_id,
                    KnowledgeNodeType.REQUIREMENT,
                    execution.requirement_id,
                )
            if execution.finding_id:
                _link(
                    KnowledgeEdgeType.TRACEABLE_TO,
                    KnowledgeNodeType.FINDING,
                    execution.finding_id,
                    KnowledgeNodeType.REQUIREMENT,
                    execution.requirement_id,
                )
            if execution.capability_id:
                _link(
                    KnowledgeEdgeType.IMPLEMENTS,
                    KnowledgeNodeType.REQUIREMENT,
                    execution.requirement_id,
                    KnowledgeNodeType.CAPABILITY,
                    execution.capability_id,
                )
            if execution.document_id:
                _link(
                    KnowledgeEdgeType.REFERENCES,
                    KnowledgeNodeType.DOCUMENT,
                    execution.document_id,
                    KnowledgeNodeType.REQUIREMENT,
                    execution.requirement_id,
                )
            if execution.recommendation_id and execution.finding_id:
                _link(
                    KnowledgeEdgeType.RELATED_TO,
                    KnowledgeNodeType.RECOMMENDATION,
                    execution.recommendation_id,
                    KnowledgeNodeType.FINDING,
                    execution.finding_id,
                )
            if execution.capability_id and execution.document_id:
                _link(
                    KnowledgeEdgeType.USES,
                    KnowledgeNodeType.CAPABILITY,
                    execution.capability_id,
                    KnowledgeNodeType.DOCUMENT,
                    execution.document_id,
                )

        return tuple(edges.values())

    def _enabled_edge_types(self) -> frozenset[KnowledgeEdgeType]:
        """Return the governed edge types whose rule is enabled and policy-gated on."""
        types: set[KnowledgeEdgeType] = set()
        for rule in self._catalog.by_family(KnowledgeGraphRuleFamily.EDGE):
            if rule.edge_type is None:
                continue
            if getattr(self._policy.capability_switches, str(rule.policy_reference)):
                types.add(rule.edge_type)
        return frozenset(types)
