"""Quality Governance Framework (CAP-080).

The governed subsystem that owns Quality Governance for a Requirement Intelligence
run: policy evaluation, quality assessment, release decisions, and governance
findings. It is a **consumer only** of the three completed peer results —
``GroundingResult``, ``ValidationResult``, ``CP1Result`` — and owns none of the
Engineering Context, Analysis, Grounding, Validation, CP1, Execution Package,
Reporting, or Serialization upstream of it (ADR-0017).

**Runtime status (CAP-080C):** every layer is implemented behind its frozen contract —
rule evaluation (CAP-080B), assessment (CAP-080B.1), decision (CAP-080B.2), and the
:class:`DefaultQualityGovernanceService` that sequences them via a private pipeline
(CAP-080C). The subsystem is **not yet wired into the Requirement Intelligence execution
pipeline** (nothing calls ``evaluate`` at runtime), so runtime behaviour is byte-identical
and the golden baseline is unchanged; CLI and execution-package integration land in
CAP-080D. Governed by ADR-0017.
"""

from __future__ import annotations

from requirement_intelligence.quality_governance.assessment import (
    ASSESSMENT_OUTCOME_VERSION,
    ASSESSMENT_POLICY_VERSION,
    DEFAULT_ASSESSMENT_POLICY_ID,
    QUALITY_ASSESSMENT_RESULT_VERSION,
    AssessmentConflictPolicy,
    AssessmentDistributionEntry,
    AssessmentFindingReference,
    AssessmentLevel,
    AssessmentOutcome,
    AssessmentPolicy,
    AssessmentPolicyBuilder,
    AssessmentStatistics,
    AssessmentSummary,
    AssessmentWeights,
    DeterministicQualityAssessmentEngine,
    QualityAssessmentEngine,
    QualityAssessmentResult,
    default_assessment_policy,
)
from requirement_intelligence.quality_governance.builder import QualityGovernanceResultBuilder
from requirement_intelligence.quality_governance.decision import (
    DECISION_POLICY_VERSION,
    DECISION_VERSION,
    DEFAULT_DECISION_POLICY_ID,
    QUALITY_DECISION_RESULT_VERSION,
    DecisionExplanation,
    DecisionPolicy,
    DecisionPolicyBuilder,
    DecisionRule,
    DecisionStatistics,
    DecisionSummary,
    DeterministicQualityDecisionEngine,
    QualityDecisionEngine,
    QualityDecisionResult,
    default_decision_policy,
)
from requirement_intelligence.quality_governance.evaluation import (
    RULE_EVALUATION_RESULT_VERSION,
    RULE_EVALUATION_VERSION,
    DeterministicQualityRuleEvaluator,
    QualityRuleEvaluator,
    RuleCategory,
    RuleCategoryCount,
    RuleEvaluation,
    RuleEvaluationResult,
    RuleEvaluationStatistics,
    RuleEvaluationStatus,
    RuleEvaluationSummary,
    RuleSeverityCount,
)
from requirement_intelligence.quality_governance.identity import (
    AssessmentOutcomeVersion,
    AssessmentPolicyId,
    AssessmentPolicyVersion,
    DecisionPolicyId,
    DecisionPolicyVersion,
    DecisionVersion,
    QualityAssessmentId,
    QualityAssessmentResultId,
    QualityAssessmentResultVersion,
    QualityAssessmentVersion,
    QualityDecisionResultId,
    QualityDecisionResultVersion,
    QualityGovernanceResultId,
    QualityGovernanceResultVersion,
    QualityGovernanceVersion,
    QualityPolicyId,
    QualityPolicyVersion,
    RuleEvaluationId,
    RuleEvaluationResultId,
    RuleEvaluationResultVersion,
    RuleEvaluationVersion,
)
from requirement_intelligence.quality_governance.models import (
    QUALITY_ASSESSMENT_VERSION,
    QUALITY_GOVERNANCE_RESULT_VERSION,
    ConsumedResultReference,
    QualityAssessment,
    QualityDecision,
    QualityFinding,
    QualityFindingCategory,
    QualityFindingCategoryCount,
    QualityGovernanceResult,
    QualityInputSource,
    QualitySeverity,
    QualitySummary,
)
from requirement_intelligence.quality_governance.policy import (
    DEFAULT_QUALITY_POLICY_ID,
    QualityPolicy,
    QualityPolicyBuilder,
    QualityReleaseRules,
    QualitySeverityThresholds,
    QualityThresholds,
    default_quality_policy,
)
from requirement_intelligence.quality_governance.quality_governance_service import (
    DefaultQualityGovernanceService,
    QualityGovernanceService,
)
from requirement_intelligence.quality_governance.version import (
    QUALITY_GOVERNANCE_FRAMEWORK_VERSION,
    QUALITY_POLICY_VERSION,
)

__all__ = [
    "ASSESSMENT_OUTCOME_VERSION",
    "ASSESSMENT_POLICY_VERSION",
    "DECISION_POLICY_VERSION",
    "DECISION_VERSION",
    "DEFAULT_ASSESSMENT_POLICY_ID",
    "DEFAULT_DECISION_POLICY_ID",
    "DEFAULT_QUALITY_POLICY_ID",
    "QUALITY_ASSESSMENT_RESULT_VERSION",
    "QUALITY_ASSESSMENT_VERSION",
    "QUALITY_DECISION_RESULT_VERSION",
    "QUALITY_GOVERNANCE_FRAMEWORK_VERSION",
    "QUALITY_GOVERNANCE_RESULT_VERSION",
    "QUALITY_POLICY_VERSION",
    "RULE_EVALUATION_RESULT_VERSION",
    "RULE_EVALUATION_VERSION",
    "AssessmentConflictPolicy",
    "AssessmentDistributionEntry",
    "AssessmentFindingReference",
    "AssessmentLevel",
    "AssessmentOutcome",
    "AssessmentOutcomeVersion",
    "AssessmentPolicy",
    "AssessmentPolicyBuilder",
    "AssessmentPolicyId",
    "AssessmentPolicyVersion",
    "AssessmentStatistics",
    "AssessmentSummary",
    "AssessmentWeights",
    "ConsumedResultReference",
    "DecisionExplanation",
    "DecisionPolicy",
    "DecisionPolicyBuilder",
    "DecisionPolicyId",
    "DecisionPolicyVersion",
    "DecisionRule",
    "DecisionStatistics",
    "DecisionSummary",
    "DecisionVersion",
    "DefaultQualityGovernanceService",
    "DeterministicQualityAssessmentEngine",
    "DeterministicQualityDecisionEngine",
    "DeterministicQualityRuleEvaluator",
    "QualityAssessment",
    "QualityAssessmentEngine",
    "QualityAssessmentId",
    "QualityAssessmentResult",
    "QualityAssessmentResultId",
    "QualityAssessmentResultVersion",
    "QualityAssessmentVersion",
    "QualityDecision",
    "QualityDecisionEngine",
    "QualityDecisionResult",
    "QualityDecisionResultId",
    "QualityDecisionResultVersion",
    "QualityFinding",
    "QualityFindingCategory",
    "QualityFindingCategoryCount",
    "QualityGovernanceResult",
    "QualityGovernanceResultBuilder",
    "QualityGovernanceResultId",
    "QualityGovernanceResultVersion",
    "QualityGovernanceService",
    "QualityGovernanceVersion",
    "QualityInputSource",
    "QualityPolicy",
    "QualityPolicyBuilder",
    "QualityPolicyId",
    "QualityPolicyVersion",
    "QualityReleaseRules",
    "QualityRuleEvaluator",
    "QualitySeverity",
    "QualitySeverityThresholds",
    "QualitySummary",
    "QualityThresholds",
    "RuleCategory",
    "RuleCategoryCount",
    "RuleEvaluation",
    "RuleEvaluationId",
    "RuleEvaluationResult",
    "RuleEvaluationResultId",
    "RuleEvaluationResultVersion",
    "RuleEvaluationStatistics",
    "RuleEvaluationStatus",
    "RuleEvaluationSummary",
    "RuleEvaluationVersion",
    "RuleSeverityCount",
    "default_assessment_policy",
    "default_decision_policy",
    "default_quality_policy",
]
