"""Typed identity value objects for the Quality Governance Framework."""

from __future__ import annotations

from requirement_intelligence.quality_governance.identity.quality_identity import (
    AssessmentOutcomeVersion,
    AssessmentPolicyId,
    AssessmentPolicyVersion,
    DecisionPolicyId,
    DecisionPolicyVersion,
    DecisionVersion,
    QualityAssessmentId,
    QualityAssessmentResultId,
    QualityAssessmentResultVersion,
    QualityAssessmentVersion,
    QualityDecisionResultId,
    QualityDecisionResultVersion,
    QualityGovernanceResultId,
    QualityGovernanceResultVersion,
    QualityGovernanceVersion,
    QualityPolicyId,
    QualityPolicyVersion,
    RuleEvaluationId,
    RuleEvaluationResultId,
    RuleEvaluationResultVersion,
    RuleEvaluationVersion,
)

__all__ = [
    "AssessmentOutcomeVersion",
    "AssessmentPolicyId",
    "AssessmentPolicyVersion",
    "DecisionPolicyId",
    "DecisionPolicyVersion",
    "DecisionVersion",
    "QualityAssessmentId",
    "QualityAssessmentResultId",
    "QualityAssessmentResultVersion",
    "QualityAssessmentVersion",
    "QualityDecisionResultId",
    "QualityDecisionResultVersion",
    "QualityGovernanceResultId",
    "QualityGovernanceResultVersion",
    "QualityGovernanceVersion",
    "QualityPolicyId",
    "QualityPolicyVersion",
    "RuleEvaluationId",
    "RuleEvaluationResultId",
    "RuleEvaluationResultVersion",
    "RuleEvaluationVersion",
]
