"""Builder for the governed default :class:`QualityRuleCatalog` (CAP-080B).

Construction only. It assembles the framework's default governed rule catalogue — a
deterministic, immutable value — and rejects nothing beyond the models' own field and
invariant constraints. It performs no evaluation, reads no upstream result, and has no
runtime consumers.

The catalogue is **governed data**. Future rule additions, removals, or retunings
require only a builder change (a versioned catalogue change under the golden re-baseline
procedure), never an evaluator code change — mirroring the policy discipline (ADR-0017
Recommendation 2). Every numeric bound lives in the :class:`QualityPolicy`; a rule here
only names *which* policy field bounds it (:class:`QualityThresholdRef`).

The default catalogue spans all six governed :class:`RuleCategory` values — grounding,
validation, CP1, cross-subsystem, mandatory-release, and advisory — so the deterministic
evaluator exercises every category from day one.
"""

from __future__ import annotations

from requirement_intelligence.quality_governance.evaluation.models import RuleCategory
from requirement_intelligence.quality_governance.models.enums import QualitySeverity
from requirement_intelligence.quality_governance.rules.quality_rule import (
    QualityMetric,
    QualityMetricSubsystem,
    QualityReleaseToggle,
    QualityRule,
    QualityThresholdRef,
    RuleComparator,
    RuleType,
)
from requirement_intelligence.quality_governance.rules.quality_rule_catalog import (
    QUALITY_RULE_CATALOG_VERSION,
    QualityRuleCatalog,
)


class QualityRuleBuilder:
    """Assemble the governed default :class:`QualityRuleCatalog`."""

    def build(self) -> QualityRuleCatalog:
        """Return the framework's default governed rule catalogue, in canonical order."""
        rules = (
            # ---- Grounding -------------------------------------------------------
            QualityRule(
                rule_id="QG-GRD-001",
                rule_name="Grounding score meets the failure bar",
                category=RuleCategory.GROUNDING,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.THRESHOLD,
                description="The grounding score must clear the governed failure minimum.",
                metric=QualityMetric.GROUNDING_SCORE,
                comparator=RuleComparator.AT_LEAST,
                threshold_ref=QualityThresholdRef.FAILURE_MIN_GROUNDING_SCORE,
                evaluation_order=10,
                recommendation="Improve requirement grounding until the score clears the bar.",
                applicable_subsystem=QualityMetricSubsystem.GROUNDING,
                tags=("grounding", "score"),
            ),
            QualityRule(
                rule_id="QG-GRD-002",
                rule_name="Grounding score meets the warning bar",
                category=RuleCategory.GROUNDING,
                severity=QualitySeverity.WARNING,
                rule_type=RuleType.THRESHOLD,
                description="The grounding score should clear the governed warning minimum.",
                metric=QualityMetric.GROUNDING_SCORE,
                comparator=RuleComparator.AT_LEAST,
                threshold_ref=QualityThresholdRef.WARNING_MIN_GROUNDING_SCORE,
                evaluation_order=20,
                recommendation="Raise grounding coverage to clear the warning bar.",
                applicable_subsystem=QualityMetricSubsystem.GROUNDING,
                tags=("grounding", "score"),
            ),
            QualityRule(
                rule_id="QG-GRD-003",
                rule_name="Hallucination rate within the failure bar",
                category=RuleCategory.GROUNDING,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.THRESHOLD,
                description="The hallucination rate must not exceed the governed failure maximum.",
                metric=QualityMetric.HALLUCINATION_RATE,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.FAILURE_MAX_HALLUCINATION_RATE,
                evaluation_order=30,
                recommendation="Remove unsupported requirements to lower the hallucination rate.",
                applicable_subsystem=QualityMetricSubsystem.GROUNDING,
                tags=("grounding", "hallucination"),
            ),
            QualityRule(
                rule_id="QG-GRD-004",
                rule_name="Hallucination rate within the warning bar",
                category=RuleCategory.GROUNDING,
                severity=QualitySeverity.WARNING,
                rule_type=RuleType.THRESHOLD,
                description="The hallucination rate should stay within the warning maximum.",
                metric=QualityMetric.HALLUCINATION_RATE,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.WARNING_MAX_HALLUCINATION_RATE,
                evaluation_order=40,
                recommendation="Reduce weakly-supported requirements to clear the warning bar.",
                applicable_subsystem=QualityMetricSubsystem.GROUNDING,
                tags=("grounding", "hallucination"),
            ),
            QualityRule(
                rule_id="QG-GRD-005",
                rule_name="Average grounding confidence meets the failure bar",
                category=RuleCategory.GROUNDING,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.THRESHOLD,
                description="Average grounding confidence must clear the governed failure minimum.",
                metric=QualityMetric.AVERAGE_CONFIDENCE,
                comparator=RuleComparator.AT_LEAST,
                threshold_ref=QualityThresholdRef.FAILURE_MIN_CONFIDENCE,
                evaluation_order=50,
                recommendation="Strengthen evidence links to raise average confidence.",
                applicable_subsystem=QualityMetricSubsystem.GROUNDING,
                tags=("grounding", "confidence"),
            ),
            QualityRule(
                rule_id="QG-GRD-006",
                rule_name="Evidence coverage meets the failure bar",
                category=RuleCategory.GROUNDING,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.THRESHOLD,
                description="Evidence coverage must clear the governed failure minimum.",
                metric=QualityMetric.EVIDENCE_COVERAGE,
                comparator=RuleComparator.AT_LEAST,
                threshold_ref=QualityThresholdRef.FAILURE_MIN_EVIDENCE_COVERAGE,
                evaluation_order=60,
                recommendation="Attach evidence to uncovered requirements.",
                applicable_subsystem=QualityMetricSubsystem.GROUNDING,
                tags=("grounding", "evidence"),
            ),
            # ---- Validation ------------------------------------------------------
            QualityRule(
                rule_id="QG-VAL-001",
                rule_name="Validation critical findings within budget",
                category=RuleCategory.VALIDATION,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.COUNT,
                description="Critical validation findings must stay within the governed budget.",
                metric=QualityMetric.VALIDATION_CRITICAL_COUNT,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.VALIDATION_MAX_CRITICAL,
                evaluation_order=70,
                recommendation="Resolve critical validation issues before release.",
                applicable_subsystem=QualityMetricSubsystem.VALIDATION,
                tags=("validation", "critical"),
            ),
            QualityRule(
                rule_id="QG-VAL-002",
                rule_name="Validation error findings within budget",
                category=RuleCategory.VALIDATION,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.COUNT,
                description="Error validation findings must stay within the governed budget.",
                metric=QualityMetric.VALIDATION_ERROR_COUNT,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.VALIDATION_MAX_HIGH,
                evaluation_order=80,
                recommendation="Resolve error-level validation issues before release.",
                applicable_subsystem=QualityMetricSubsystem.VALIDATION,
                tags=("validation", "error"),
            ),
            QualityRule(
                rule_id="QG-VAL-003",
                rule_name="Validation warning findings within budget",
                category=RuleCategory.VALIDATION,
                severity=QualitySeverity.WARNING,
                rule_type=RuleType.COUNT,
                description="Warning validation findings should stay within the governed budget.",
                metric=QualityMetric.VALIDATION_WARNING_COUNT,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.VALIDATION_MAX_MEDIUM,
                evaluation_order=90,
                recommendation="Review warning-level validation issues.",
                applicable_subsystem=QualityMetricSubsystem.VALIDATION,
                tags=("validation", "warning"),
            ),
            # ---- CP1 -------------------------------------------------------------
            QualityRule(
                rule_id="QG-CP1-001",
                rule_name="CP1 blocking findings within budget",
                category=RuleCategory.CP1,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.COUNT,
                description="Blocking (FAIL) CP1 findings must stay within the governed budget.",
                metric=QualityMetric.CP1_BLOCKING_FINDINGS,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.CP1_MAX_CRITICAL,
                evaluation_order=100,
                recommendation="Resolve blocking engineering-readiness findings before release.",
                applicable_subsystem=QualityMetricSubsystem.CP1,
                tags=("cp1", "blocking"),
            ),
            QualityRule(
                rule_id="QG-CP1-002",
                rule_name="CP1 warn findings within budget",
                category=RuleCategory.CP1,
                severity=QualitySeverity.WARNING,
                rule_type=RuleType.COUNT,
                description="Warn CP1 findings should stay within the governed budget.",
                metric=QualityMetric.CP1_WARN_FINDINGS,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.CP1_MAX_HIGH,
                evaluation_order=110,
                recommendation="Review warn-level engineering-readiness findings.",
                applicable_subsystem=QualityMetricSubsystem.CP1,
                tags=("cp1", "warn"),
            ),
            # ---- Cross-subsystem -------------------------------------------------
            QualityRule(
                rule_id="QG-XSS-001",
                rule_name="Validation passed while grounding failed",
                category=RuleCategory.CROSS_SUBSYSTEM,
                severity=QualitySeverity.WARNING,
                rule_type=RuleType.CROSS_LAYER,
                description="Flag the anomaly of a passing validation over failing grounding.",
                metric=QualityMetric.CROSS_VALIDATION_PASS_GROUNDING_FAIL,
                comparator=RuleComparator.MUST_NOT_HOLD,
                threshold_ref=QualityThresholdRef.NONE,
                evaluation_order=120,
                recommendation="Reconcile validation success with weak grounding.",
                applicable_subsystem=QualityMetricSubsystem.CROSS,
                tags=("cross_subsystem", "anomaly"),
            ),
            QualityRule(
                rule_id="QG-XSS-002",
                rule_name="CP1 passed while grounding failed",
                category=RuleCategory.CROSS_SUBSYSTEM,
                severity=QualitySeverity.WARNING,
                rule_type=RuleType.CROSS_LAYER,
                description="Flag the anomaly of a passing CP1 over failing grounding.",
                metric=QualityMetric.CROSS_CP1_PASS_GROUNDING_FAIL,
                comparator=RuleComparator.MUST_NOT_HOLD,
                threshold_ref=QualityThresholdRef.NONE,
                evaluation_order=130,
                recommendation="Reconcile engineering readiness with weak grounding.",
                applicable_subsystem=QualityMetricSubsystem.CROSS,
                tags=("cross_subsystem", "anomaly"),
            ),
            # ---- Mandatory release ----------------------------------------------
            QualityRule(
                rule_id="QG-REL-001",
                rule_name="Mandatory: block on hallucination",
                category=RuleCategory.MANDATORY_RELEASE,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.MANDATORY_GATE,
                description="A hallucination rate over the failure bar blocks release.",
                metric=QualityMetric.HALLUCINATION_RATE,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.FAILURE_MAX_HALLUCINATION_RATE,
                governing_toggle=QualityReleaseToggle.BLOCK_ON_HALLUCINATION,
                mandatory=True,
                evaluation_order=140,
                recommendation="Remove hallucinated requirements; release is blocked otherwise.",
                applicable_subsystem=QualityMetricSubsystem.GROUNDING,
                tags=("mandatory_release", "hallucination"),
            ),
            QualityRule(
                rule_id="QG-REL-002",
                rule_name="Mandatory: block on validation failure",
                category=RuleCategory.MANDATORY_RELEASE,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.MANDATORY_GATE,
                description="A failing validation verdict blocks release.",
                metric=QualityMetric.VALIDATION_FAILING_VERDICT,
                comparator=RuleComparator.MUST_NOT_HOLD,
                threshold_ref=QualityThresholdRef.NONE,
                governing_toggle=QualityReleaseToggle.BLOCK_ON_VALIDATION_FAILURE,
                mandatory=True,
                evaluation_order=150,
                recommendation="Resolve the failing validation verdict; release is blocked.",
                applicable_subsystem=QualityMetricSubsystem.VALIDATION,
                tags=("mandatory_release", "validation"),
            ),
            QualityRule(
                rule_id="QG-REL-003",
                rule_name="Mandatory: block on CP1 failure",
                category=RuleCategory.MANDATORY_RELEASE,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.MANDATORY_GATE,
                description="A failing CP1 verdict blocks release.",
                metric=QualityMetric.CP1_FAILING_VERDICT,
                comparator=RuleComparator.MUST_NOT_HOLD,
                threshold_ref=QualityThresholdRef.NONE,
                governing_toggle=QualityReleaseToggle.BLOCK_ON_CP1_FAILURE,
                mandatory=True,
                evaluation_order=160,
                recommendation="Resolve the failing CP1 verdict; release is blocked.",
                applicable_subsystem=QualityMetricSubsystem.CP1,
                tags=("mandatory_release", "cp1"),
            ),
            QualityRule(
                rule_id="QG-REL-004",
                rule_name="Mandatory: require engineering readiness",
                category=RuleCategory.MANDATORY_RELEASE,
                severity=QualitySeverity.FAILURE,
                rule_type=RuleType.MANDATORY_GATE,
                description="Release requires a passing CP1 engineering-readiness verdict.",
                metric=QualityMetric.ENGINEERING_NOT_READY,
                comparator=RuleComparator.MUST_NOT_HOLD,
                threshold_ref=QualityThresholdRef.NONE,
                governing_toggle=QualityReleaseToggle.REQUIRE_ENGINEERING_READINESS,
                mandatory=True,
                evaluation_order=170,
                recommendation="Meet engineering readiness; release is blocked otherwise.",
                applicable_subsystem=QualityMetricSubsystem.CP1,
                tags=("mandatory_release", "readiness"),
            ),
            # ---- Advisory --------------------------------------------------------
            QualityRule(
                rule_id="QG-ADV-001",
                rule_name="Validation info findings within advisory budget",
                category=RuleCategory.ADVISORY,
                severity=QualitySeverity.INFO,
                rule_type=RuleType.ADVISORY,
                description="Record when informational validation findings exceed the budget.",
                metric=QualityMetric.VALIDATION_INFO_COUNT,
                comparator=RuleComparator.AT_MOST,
                threshold_ref=QualityThresholdRef.VALIDATION_MAX_LOW,
                evaluation_order=180,
                recommendation="Informational only; no release action required.",
                applicable_subsystem=QualityMetricSubsystem.VALIDATION,
                tags=("advisory", "info"),
            ),
        )
        return QualityRuleCatalog(catalog_version=QUALITY_RULE_CATALOG_VERSION, rules=rules)


def default_quality_rule_catalog() -> QualityRuleCatalog:
    """Return the framework's default governed rule catalogue."""
    return QualityRuleBuilder().build()
