"""Multi-AC fan-out: proving the ALREADY-GENERIC generator core against
authored, multi-scenario content.

*** SYNTHETIC FIXTURES -- READ BEFORE TRUSTING ANY NUMBER IN THIS FILE ***
Every `TestableRequirement` and every piece of raw scenario content in this
module is HAND-CONSTRUCTED. The requirements are built through the contract's
own constructor (`build_testable_requirement`), so their ids are real,
platform-assigned, content-addressed values -- but the underlying content
(titles, acceptance criteria, and every scenario) is authored by this test
file, not emitted by Layer 1 and not generated by a live model. This is
legitimate as GENERATOR-CORE test fixture material (exactly like every other
`_requirement()`/raw-content pair in `test_feature_engineering_generation_core.py`),
and it is NOT real-world evidence: it must never be cited as a Layer 1
emission or used to estimate real model failure rates. The live-sampling
task (CAP context) already established the real corpus is single-AC-only and
content-stable against the one available evidence set -- these fixtures fill
exactly the multi-AC/multi-scenario gap that corpus cannot reach.

Why no core code changes were needed
-------------------------------------
Pre-flight for this task found `feature_engineering/generation/assembler.py`
already generic over an arbitrary number of scenarios and an arbitrary
per-scenario `@AC-*` tag set: it discovers scenarios by parsing whatever the
content generator returns (`for child in source.feature["children"]`), mints
one `@SCN-*` per scenario found, tracks AC coverage as a floor ("every AC-*
has >=1 mapped SCN-*", ADR-0043 D5's own CP2-gate wording), and computes the
homogeneity hoist over however many scenarios exist. Neither ADR-0043 D2/D5
nor the governed `generate_feature` v1.1.0 prompt specify an exact
scenario-per-AC ratio -- the prompt's own TASK section says only "every
acceptance criterion must be exercised by at least one scenario" and its TAG
PLACEMENT section explicitly permits the inverse too ("A scenario may carry
more than one ac_id tag if it exercises more than one criterion"). Fan-out
granularity is therefore a content-generation-time (model) decision under a
coverage floor, not a platform mechanism -- there was nothing to build. This
module exercises that already-generic mechanism against multi-scenario
content it had never been run against (2-AC, 3-AC, a single AC covered by
two scenarios, and deliberately-malformed content), closing a TEST-COVERAGE
gap, not a functionality gap.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from contracts.testable_requirement import (
    AcceptanceCriterionInput,
    Category,
    PolarityHint,
    Priority,
    TestableRequirement,
    build_testable_requirement,
)
from feature_engineering.generation import (
    FeatureGenerationError,
    StubFeatureContentGenerator,
    generate_feature_file,
)

# ---------------------------------------------------------------------------
# SYNTHETIC fixtures -- hand-authored, real ids via build_testable_requirement.
# ---------------------------------------------------------------------------


def _two_ac_requirement() -> TestableRequirement:
    """SYNTHETIC: 2 ACs, one POSITIVE, one NEGATIVE."""
    return build_testable_requirement(
        title="User can reset password",
        component="auth",
        functional_tag="@auth",
        priority=Priority.HIGH,
        traces_to=(),
        narrative="Users need a self-service password reset flow.",
        acceptance_criteria=[
            AcceptanceCriterionInput(
                category=Category.FUNCTIONAL,
                statement="User receives a password reset email",
                polarity_hints=(PolarityHint.POSITIVE,),
            ),
            AcceptanceCriterionInput(
                category=Category.FUNCTIONAL,
                statement="Expired reset link is rejected",
                polarity_hints=(PolarityHint.NEGATIVE,),
            ),
        ],
    )


def _three_ac_requirement() -> TestableRequirement:
    """SYNTHETIC: 3 ACs spanning POSITIVE, NEGATIVE, and BOUNDARY."""
    return build_testable_requirement(
        title="User can view account balance",
        component="accounts",
        functional_tag="@accounts",
        priority=Priority.MEDIUM,
        traces_to=(),
        narrative="Balance display must respect lockout policy and rounding rules.",
        acceptance_criteria=[
            AcceptanceCriterionInput(
                category=Category.FUNCTIONAL,
                statement="User can view their current account balance",
                polarity_hints=(PolarityHint.POSITIVE,),
            ),
            AcceptanceCriterionInput(
                category=Category.SECURITY,
                statement="Balance display is hidden after 3 failed PIN attempts",
                polarity_hints=(PolarityHint.NEGATIVE,),
            ),
            AcceptanceCriterionInput(
                category=Category.FUNCTIONAL,
                statement="Balance rounds correctly at the minimum currency unit boundary",
                polarity_hints=(PolarityHint.BOUNDARY,),
            ),
        ],
    )


def _polarity_full_ac_requirement() -> TestableRequirement:
    """SYNTHETIC: 1 AC carrying all three polarity hints together -- the
    prompt's own instruction ("covered by a scenario or an Examples row, not
    only its positive path") lets this legitimately fan out to more than one
    scenario for a single AC, which this fixture exercises directly."""
    return build_testable_requirement(
        title="Login attempts are validated against lockout policy",
        component="auth",
        functional_tag="@auth",
        priority=Priority.HIGH,
        traces_to=(),
        narrative="Login must succeed normally and reject attempts beyond the lockout boundary.",
        acceptance_criteria=[
            AcceptanceCriterionInput(
                category=Category.SECURITY,
                statement="Login attempt is validated against the account lockout policy",
                polarity_hints=(
                    PolarityHint.POSITIVE,
                    PolarityHint.NEGATIVE,
                    PolarityHint.BOUNDARY,
                ),
            ),
        ],
    )


def _long_compound_ac_requirement() -> TestableRequirement:
    """SYNTHETIC: one AC with a long, compound statement -- the shape most
    likely to tempt a real model into an oversized scenario or an
    over-length step, used to motivate (not directly cause) the deliberately
    -dirty rejection fixtures below."""
    return build_testable_requirement(
        title="Checkout validates multiple conditions in one pass",
        component="checkout",
        functional_tag="@checkout",
        priority=Priority.HIGH,
        traces_to=(),
        narrative="A single checkout submission must validate several independent conditions.",
        acceptance_criteria=[
            AcceptanceCriterionInput(
                category=Category.FUNCTIONAL,
                statement=(
                    "When a user submits a payment that includes a shipping address outside "
                    "the supported regions, a partial discount code, and a saved payment "
                    "method nearing its expiration date, the system shall validate each "
                    "condition independently, apply the appropriate proration rules, and "
                    "surface a single consolidated validation summary to the user without "
                    "silently dropping any individual failure reason."
                ),
                polarity_hints=(PolarityHint.POSITIVE, PolarityHint.NEGATIVE),
            ),
        ],
    )


def _two_ac_clean_content(req: TestableRequirement) -> str:
    ac1, ac2 = req.acceptance_criteria
    return f"""@smoke @{ac1.criterion_id} @SCN-PENDING
Scenario: User receives a password reset email
  Given a registered user requests a password reset
  When the reset request is submitted
  Then a reset email is sent

@regression @{ac2.criterion_id} @SCN-PENDING
Scenario: Expired reset link is rejected
  Given a user has an expired password reset link
  When the user opens the reset link
  Then the system rejects the expired link
"""


def _three_ac_clean_content(req: TestableRequirement) -> str:
    ac1, ac2, ac3 = req.acceptance_criteria
    # @balance is authored on every scenario (a genuine, deliberate
    # cross-scenario homogenous functional tag); @security only on the
    # second, so it must stay scenario-level.
    return f"""@balance @{ac1.criterion_id} @SCN-PENDING
Scenario: User views current account balance
  Given a logged-in user with an active account
  When the user opens the balance view
  Then the current account balance is displayed

@balance @security @{ac2.criterion_id} @SCN-PENDING
Scenario: Balance is hidden after repeated failed PIN attempts
  Given a user has entered an incorrect PIN three times
  When the user attempts to view the balance again
  Then the balance is hidden and re-authentication is required

@balance @{ac3.criterion_id} @SCN-PENDING
Scenario Outline: Balance rounds correctly at the minimum currency unit boundary
  Given an account balance of "<raw_balance>"
  When the balance is displayed
  Then the displayed balance is "<rounded_balance>"
  Examples:
    | raw_balance | rounded_balance |
    | 10.005 | 10.01 |
    | 10.004 | 10.00 |
"""


def _polarity_full_clean_content(req: TestableRequirement) -> str:
    (ac,) = req.acceptance_criteria
    # Both scenarios cover the SAME (only) AC -- one for the positive path,
    # one (an outline) for the negative/boundary paths the polarity hints
    # call for. @login is on both scenarios too, so both @login and the AC
    # tag are genuinely homogenous here and correctly hoist.
    return f"""@login @{ac.criterion_id} @SCN-PENDING
Scenario: Successful login within lockout policy
  Given a user with no prior failed login attempts
  When the user logs in with correct credentials
  Then the login succeeds

@login @{ac.criterion_id} @SCN-PENDING
Scenario Outline: Login attempts beyond the lockout boundary are rejected
  Given a user has "<failed_attempts>" prior failed login attempts
  When the user attempts to log in again
  Then the outcome is "<expected_outcome>"
  Examples:
    | failed_attempts | expected_outcome |
    | 4 | rejected |
    | 5 | locked_out |
"""


class TestTwoAndThreeAcFanOut:
    def test_two_ac_requirement_produces_two_correctly_tagged_scenarios(
        self, tmp_path: Path
    ) -> None:
        req = _two_ac_requirement()
        raw = _two_ac_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )

        assert result.lint_result.is_clean
        assert len(result.scenarios) == 2
        assert result.fully_covered
        assert all(result.acceptance_criteria_coverage.values())
        scn_ids = {s.scn_id for s in result.scenarios}
        assert len(scn_ids) == 2  # distinct

        print("=== 2-AC assembled .feature ===")
        print(result.content)

    def test_three_ac_requirement_produces_three_correctly_tagged_scenarios(
        self, tmp_path: Path
    ) -> None:
        req = _three_ac_requirement()
        raw = _three_ac_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )

        assert result.lint_result.is_clean
        assert len(result.scenarios) == 3
        assert result.fully_covered
        assert all(result.acceptance_criteria_coverage.values())
        scn_ids = {s.scn_id for s in result.scenarios}
        assert len(scn_ids) == 3  # distinct

        print("=== 3-AC assembled .feature ===")
        print(result.content)

    def test_polarity_full_ac_two_scenarios_share_one_ac_tag(self, tmp_path: Path) -> None:
        req = _polarity_full_ac_requirement()
        raw = _polarity_full_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )

        assert result.lint_result.is_clean
        assert len(result.scenarios) == 2
        assert result.fully_covered
        # Both scenarios reference the requirement's one AC.
        (ac,) = req.acceptance_criteria
        assert all(ac.criterion_id in s.ac_ids for s in result.scenarios)
        scn_ids = {s.scn_id for s in result.scenarios}
        assert len(scn_ids) == 2  # distinct even though they share an AC

        print("=== single-AC, two-scenario assembled .feature ===")
        print(result.content)


class TestHoistFiresOnlyOnGenuineHomogeneity:
    def test_three_ac_case_ac_tags_do_not_wrongly_hoist(self, tmp_path: Path) -> None:
        """3 distinct ACs, one per scenario: none of the @AC-* tags are
        present on every scenario, so none may hoist -- proving the hoist
        does not fire merely because a feature has several AC tags."""
        req = _three_ac_requirement()
        raw = _three_ac_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )

        feature_tag_line = result.content.splitlines()[0]
        for ac in req.acceptance_criteria:
            assert f"@{ac.criterion_id}" not in feature_tag_line
            assert f"@{ac.criterion_id}" in result.content  # still present, at scenario level

    def test_three_ac_case_functional_tag_on_all_scenarios_still_hoists(
        self, tmp_path: Path
    ) -> None:
        """@balance is authored on all three scenarios in the same fixture
        above -- contrasting proof that genuine homogeneity still hoists in
        a real multi-scenario (not just single-scenario) feature."""
        req = _three_ac_requirement()
        raw = _three_ac_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )

        feature_tag_line = result.content.splitlines()[0]
        assert "@balance" in feature_tag_line
        assert "@security" not in feature_tag_line  # only on one scenario -- must not hoist

    def test_single_ac_shared_by_two_scenarios_correctly_hoists(self, tmp_path: Path) -> None:
        """The polarity fixture: with only one AC and both scenarios
        covering it, the AC tag IS genuinely homogenous (present on every
        scenario) and correctly hoists -- the mirror-image case of the two
        tests above."""
        req = _polarity_full_ac_requirement()
        raw = _polarity_full_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )

        (ac,) = req.acceptance_criteria
        feature_tag_line = result.content.splitlines()[0]
        assert f"@{ac.criterion_id}" in feature_tag_line
        assert "@login" in feature_tag_line


class TestScnIdUniquenessAndStability:
    def test_three_scenarios_yield_three_distinct_scn_ids(self, tmp_path: Path) -> None:
        req = _three_ac_requirement()
        raw = _three_ac_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )
        scn_ids = [s.scn_id for s in result.scenarios]
        assert len(scn_ids) == len(set(scn_ids)) == 3

    def test_same_fixture_yields_the_same_scn_set_across_two_independent_runs(
        self, tmp_path: Path
    ) -> None:
        req = _three_ac_requirement()
        raw = _three_ac_clean_content(req)
        first = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )
        second = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )
        assert {s.scn_id for s in first.scenarios} == {s.scn_id for s in second.scenarios}
        assert first.content == second.content

    def test_reordering_scenarios_in_raw_content_does_not_reassign_scn_ids(
        self, tmp_path: Path
    ) -> None:
        req = _three_ac_requirement()
        ac1, ac2, ac3 = req.acceptance_criteria
        forward = _three_ac_clean_content(req)
        # Same three scenarios, reversed order in the raw text.
        reversed_order = f"""@balance @{ac3.criterion_id} @SCN-PENDING
Scenario Outline: Balance rounds correctly at the minimum currency unit boundary
  Given an account balance of "<raw_balance>"
  When the balance is displayed
  Then the displayed balance is "<rounded_balance>"
  Examples:
    | raw_balance | rounded_balance |
    | 10.005 | 10.01 |
    | 10.004 | 10.00 |

@balance @security @{ac2.criterion_id} @SCN-PENDING
Scenario: Balance is hidden after repeated failed PIN attempts
  Given a user has entered an incorrect PIN three times
  When the user attempts to view the balance again
  Then the balance is hidden and re-authentication is required

@balance @{ac1.criterion_id} @SCN-PENDING
Scenario: User views current account balance
  Given a logged-in user with an active account
  When the user opens the balance view
  Then the current account balance is displayed
"""
        forward_result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: forward}), features_root=tmp_path
        )
        reversed_result = generate_feature_file(
            req,
            StubFeatureContentGenerator({req.requirement_id: reversed_order}),
            features_root=tmp_path,
        )
        forward_by_name = {s.name: s.scn_id for s in forward_result.scenarios}
        reversed_by_name = {s.name: s.scn_id for s in reversed_result.scenarios}
        assert forward_by_name == reversed_by_name


class TestAcCoverageAcrossFanOut:
    def test_three_ac_coverage_maps_each_ac_to_its_own_scenario(self, tmp_path: Path) -> None:
        req = _three_ac_requirement()
        raw = _three_ac_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )
        ac1, ac2, ac3 = req.acceptance_criteria
        by_ac = {s.ac_ids[0]: s.scn_id for s in result.scenarios}
        assert set(by_ac) == {ac1.criterion_id, ac2.criterion_id, ac3.criterion_id}
        assert result.acceptance_criteria_coverage == {
            ac1.criterion_id: True,
            ac2.criterion_id: True,
            ac3.criterion_id: True,
        }


class TestMultiScenarioRulesAreReachableAndFireCorrectly:
    """scenario-size (limit 12), no-dupe-scenario-names, and name-length's
    Scenario path (limit 90) are all unreachable with a single scenario --
    proving each now fires on multi-scenario content closes exactly the
    gap the live-sampling task could not reach with real, single-AC data."""

    def test_clean_multi_scenario_fixtures_pass_all_three_rules_by_construction(
        self, tmp_path: Path
    ) -> None:
        req = _three_ac_requirement()
        raw = _three_ac_clean_content(req)
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )
        fired = {v.rule for v in result.lint_result.violations}
        assert "scenario-size" not in fired
        assert "no-dupe-scenario-names" not in fired
        assert not any(
            v.rule == "name-length" and "Scenario" in v.message
            for v in result.lint_result.violations
        )

    def test_oversized_scenario_is_rejected_by_scenario_size(self, tmp_path: Path) -> None:
        req = _three_ac_requirement()
        (ac1, _ac2, _ac3) = req.acceptance_criteria
        oversized = f"""@{ac1.criterion_id} @SCN-PENDING
Scenario: An oversized scenario exceeding the step count limit
  Given step one
  When step two
  Then step three
  And step four
  And step five
  And step six
  And step seven
  And step eight
  And step nine
  And step ten
  And step eleven
  And step twelve
  And step thirteen
"""
        stub = StubFeatureContentGenerator({req.requirement_id: oversized})
        with pytest.raises(FeatureGenerationError) as excinfo:
            generate_feature_file(req, stub, features_root=tmp_path)

        assert excinfo.value.lint_result is not None
        rules_fired = {v.rule for v in excinfo.value.lint_result.violations}
        print(f"oversized-scenario rejection fired rules: {rules_fired}")
        assert "scenario-size" in rules_fired

    def test_duplicate_scenario_names_across_the_fan_out_are_rejected(
        self, tmp_path: Path
    ) -> None:
        req = _three_ac_requirement()
        (ac1, ac2, _ac3) = req.acceptance_criteria
        dupe_names = f"""@{ac1.criterion_id} @SCN-PENDING
Scenario: Duplicate scenario name across the fan-out
  Given a
  When b
  Then c

@{ac2.criterion_id} @SCN-PENDING
Scenario: Duplicate scenario name across the fan-out
  Given d
  When e
  Then f
"""
        stub = StubFeatureContentGenerator({req.requirement_id: dupe_names})
        with pytest.raises(FeatureGenerationError) as excinfo:
            generate_feature_file(req, stub, features_root=tmp_path)

        assert excinfo.value.lint_result is not None
        rules_fired = {v.rule for v in excinfo.value.lint_result.violations}
        print(f"duplicate-name rejection fired rules: {rules_fired}")
        assert "no-dupe-scenario-names" in rules_fired

    def test_over_length_scenario_name_on_a_non_first_scenario_is_rejected(
        self, tmp_path: Path
    ) -> None:
        """Proves name-length's Scenario path is checked per-scenario across
        the whole fan-out, not only on the first scenario found."""
        req = _three_ac_requirement()
        (ac1, ac2, _ac3) = req.acceptance_criteria
        over_length_name = (
            "This scenario name is deliberately constructed to exceed the ninety "
            "character name-length limit configured for Scenario nodes in .gherkin-lintrc"
        )
        assert len(over_length_name) > 90
        raw = f"""@{ac1.criterion_id} @SCN-PENDING
Scenario: A perfectly normal, short scenario name
  Given a
  When b
  Then c

@{ac2.criterion_id} @SCN-PENDING
Scenario: {over_length_name}
  Given d
  When e
  Then f
"""
        stub = StubFeatureContentGenerator({req.requirement_id: raw})
        with pytest.raises(FeatureGenerationError) as excinfo:
            generate_feature_file(req, stub, features_root=tmp_path)

        assert excinfo.value.lint_result is not None
        rules_fired = {v.rule for v in excinfo.value.lint_result.violations}
        print(f"over-length-name (non-first scenario) rejection fired rules: {rules_fired}")
        assert "name-length" in rules_fired

    def test_long_compound_ac_still_lints_clean_when_authored_within_limits(
        self, tmp_path: Path
    ) -> None:
        """The long/compound-AC fixture: a realistic elaborate requirement
        does not, by itself, cause a lint failure -- only elaborate,
        oversized SCENARIO CONTENT does (proven above). This isolates that
        distinction: complexity in the AC statement is not automatically
        complexity in the generated scenario."""
        req = _long_compound_ac_requirement()
        (ac,) = req.acceptance_criteria
        raw = f"""@checkout @{ac.criterion_id} @SCN-PENDING
Scenario: Checkout surfaces every validation failure in one summary
  Given a checkout submission with multiple invalid conditions
  When the submission is validated
  Then a single consolidated validation summary is shown
"""
        result = generate_feature_file(
            req, StubFeatureContentGenerator({req.requirement_id: raw}), features_root=tmp_path
        )
        assert result.lint_result.is_clean
